name: Building & Testing with Swift 5.1 via Docker

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Package
      run: docker run --rm --mount type=bind,src=$GITHUB_WORKSPACE,dst=/github_workspace -w /github_workspace swift:5.1 swift build -v
    - name: Test Package
      run: docker run --rm --mount type=bind,src=$GITHUB_WORKSPACE,dst=/github_workspace -w /github_workspace swift:5.1 swift test -v --enable-test-discovery --enable-code-coverage
    - name: Prepare Code Coverage
      run: docker run --rm --mount type=bind,src=$GITHUB_WORKSPACE,dst=/github_workspace -w /github_workspace swift:5.1 llvm-cov export -format="lcov" .build/x86_64-unknown-linux-gnu/debug/FirstOrderDeepEmbeddingPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to CodeConv.io
      run: bash <(curl https://codecov.io/bash)
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV }}
