name: Ubuntu

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker run --rm --mount type=bind,src=$GITHUB_WORKSPACE,dst=/github_workspace -w /github_workspace swift:5.1 swift build -v
    - name: Test
      run: docker run --rm --mount type=bind,src=$GITHUB_WORKSPACE,dst=/github_workspace -w /github_workspace swift:5.1 swift test -v
